apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-simple
spec:
  entrypoint: python /home/ray/samples/sample_code.py
  
  shutdownAfterJobFinishes: true

  ttlSecondsAfterFinished: 30

  rayClusterSpec:

    rayVersion: "2.47.1"

    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"

      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.47.1

    workerGroupSpecs:
    - groupName: workers
      replicas: 2
      minReplicas: 2
      maxReplicas: 2

      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.47.1
